In [ ]:
import numpy as np
import numpy.ma as ma
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
import tabulate
import random

In [ ]:
scholarship_url = 'https://raw.githubusercontent.com/qannisa/dummydataset/main/scholarship_features2.csv'

scholarship_file = pd.read_csv(scholarship_url)

In [ ]:
scholarship_file

scholarship_name  scholarship  honor_and_awards  experience   gpa
0               BCA           10                 0           1  3.25
1                BU           12                 1           0  3.00
2                BI           14                 0           1  3.00
3               BRI           16                 0           1  3.25
4               BSI           18                 1           0  3.00
5              CIMB           20                 1           1  3.25
6         dataprint           22                 1           1  3.00
7            djarum           24                 0           1  3.00
8               KSE           26                 0           1  3.00
9         pertamina           28                 0           1  3.00
10           tanoto           30                 1           1  3.00
11               XL           32                 0           1  2.80

In [ ]:
num_item_features = scholarship_file.shape [1] - 1
item_train = scholarship_file.values.tolist()

item_train = np.array(item_train)
item_train_f = item_train[:, 2:]
item_train_f= np.asarray(item_train_f).astype('float32')
print(item_train_f)
print(item_train_f.shape)

y_train = [row[1] for row in item_train]
y_train = np.asarray(y_train).astype('float32')
y_train.reshape(-1, 1)

print(y_train)
print(y_train.shape)

[[0.   1.   3.25]
 [1.   0.   3.  ]
 [0.   1.   3.  ]
 [0.   1.   3.25]
 [1.   0.   3.  ]
 [1.   1.   3.25]
 [1.   1.   3.  ]
 [0.   1.   3.  ]
 [0.   1.   3.  ]
 [0.   1.   3.  ]
 [1.   1.   3.  ]
 [0.   1.   2.8 ]]
(12, 3)
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
(12,)


In [ ]:
model_item = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu')
])

In [ ]:
cost_fn = tf.keras.losses.MeanSquaredError()
opt = tf.keras.optimizers.Adam()
model_item.compile(optimizer=opt,
              loss=cost_fn)

In [ ]:
model_item.fit(item_train_f, y_train, epochs=30)

Epoch 1/30
1/1 [==============================] - 0s 17ms/step - loss: 475.0714
Epoch 2/30
1/1 [==============================] - 0s 14ms/step - loss: 474.2655
Epoch 3/30
1/1 [==============================] - 0s 12ms/step - loss: 473.4497
Epoch 4/30
1/1 [==============================] - 0s 13ms/step - loss: 472.6233
Epoch 5/30
1/1 [==============================] - 0s 13ms/step - loss: 471.7852
Epoch 6/30
1/1 [==============================] - 0s 13ms/step - loss: 470.9323
Epoch 7/30
1/1 [==============================] - 0s 12ms/step - loss: 470.0665
Epoch 8/30
1/1 [==============================] - 0s 14ms/step - loss: 469.1867
Epoch 9/30
1/1 [==============================] - 0s 12ms/step - loss: 468.2920
Epoch 10/30
1/1 [==============================] - 0s 14ms/step - loss: 467.3823
Epoch 11/30
1/1 [==============================] - 0s 13ms/step - loss: 466.4572
Epoch 12/30
1/1 [==============================] - 0s 16ms/step - loss: 465.5158
Epoch 13/30
1/1 [====================

In [ ]:
input_item = tf.keras.layers.Input(shape=(3,))
vm = model_item(input_item)
vm = tf.linalg.l2_normalize(vm, axis=1)

print(vm)

KerasTensor(type_spec=TensorSpec(shape=(None, 64), dtype=tf.float32, name=None), name='tf.math.l2_normalize_2/l2_normalize:0', description="created by layer 'tf.math.l2_normalize_2'")


In [ ]:
user_url = 'https://raw.githubusercontent.com/qannisa/dummydataset/main/user_feature.csv'

user_file = pd.read_csv(user_url)

In [ ]:
user_file

honors  experience   gpa  scholarship_tag  \
0           0           2  3.77               10   
1           0           3  3.95               10   
2           0           1  3.46               10   
3           0           2  3.95               10   
4           3           3  3.57               10   
...       ...         ...   ...              ...   
11995       2           3  3.45               32   
11996       2           3  3.74               32   
11997       2           2  3.67               32   
11998       1           3  3.64               32   
11999       0           2  3.09               32   

                    scholarship_name  
0                 Beasiswa Bakti BCA  
1                 Beasiswa Bakti BCA  
2                 Beasiswa Bakti BCA  
3                 Beasiswa Bakti BCA  
4                 Beasiswa Bakti BCA  
...                              ...  
11995  Beasiswa XL Future Leadership  
11996  Beasiswa XL Future Leadership  
11997  Beasiswa XL Future Leadership  
11998  Beasiswa XL Future Leadership  
11999  Beasiswa XL Future Leadership  

[12000 rows x 5 columns]

In [ ]:
user_train = user_file.values.tolist()

user_train = np.array(user_train)
user_train_f = user_train[:, :-1]
user_train_f= np.asarray(user_train_f).astype('float32')
random.shuffle(user_train_f)
print(user_train_f)
print(user_train_f.shape)

y_train_u = [row[3] for row in user_train_f]
y_train_u = np.asarray(y_train_u).astype('float32')
y_train_u.reshape(-1, 1)

print(y_train_u)
print(y_train_u.shape)

[[ 0.    2.    3.77 10.  ]
 [ 0.    2.    3.77 10.  ]
 [ 0.    1.    3.46 10.  ]
 ...
 [ 0.    3.    3.26 30.  ]
 [ 3.    2.    3.61 10.  ]
 [ 1.    4.    3.81 24.  ]]
(12000, 4)
[10. 10. 10. ... 30. 10. 24.]
(12000,)


In [ ]:
model_user = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu')
])

In [ ]:
cost_fn = tf.keras.losses.MeanSquaredError()
opt = tf.keras.optimizers.Adam()
model_user.compile(optimizer=opt,
              loss=cost_fn)

In [ ]:
model_user.fit(user_train_f, y_train_u, epochs=30)

Epoch 1/30
375/375 [==============================] - 1s 2ms/step - loss: 148.3134
Epoch 2/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1321
Epoch 3/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1213
Epoch 4/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1201
Epoch 5/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1196
Epoch 6/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1196
Epoch 7/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1195
Epoch 8/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1195
Epoch 9/30
375/375 [==============================] - 1s 2ms/step - loss: 135.1194
Epoch 10/30
375/375 [==============================] - 1s 3ms/step - loss: 135.1193
Epoch 11/30
375/375 [==============================] - 1s 4ms/step - loss: 135.1192
Epoch 12/30
375/375 [==============================] - 1s 3ms/step - loss: 135.1192
E

In [ ]:
input_user = tf.keras.layers.Input(shape=(4,))
vu = model_user(input_user)
vu = tf.linalg.l2_normalize(vu, axis=1)

print(vu)

KerasTensor(type_spec=TensorSpec(shape=(None, 64), dtype=tf.float32, name=None), name='tf.math.l2_normalize_3/l2_normalize:0', description="created by layer 'tf.math.l2_normalize_3'")


In [ ]:
# compute the dot product of the two vectors vu and vm
output = tf.keras.layers.Dot(axes=1)([vu, vm])

# specify the inputs and output of the model
model = tf.keras.Model([input_user, input_item], output)

In [ ]:
cost_fn = tf.keras.losses.MeanSquaredError()
opt = tf.keras.optimizers.Adam()
model.compile(optimizer=opt,
              loss=cost_fn)

In [ ]:
model.fit([user_train_f, item_train_f], y_train_u, epochs=30)

ValueError: ignored